### ISSUE TITLE
팀장의 할일 : README.md 수정하기

### ISSUE THREAD

**Issue by gimdongwoo** [kosslab-kr/Titanium-BrandNew#36]
리파지터리 루트의 README.md 파일을 지금 하고 있는 프로젝트에 대한 내용으로 수정하고 commit+push 합니다.

아래 파일을 참고하여, Markdown 문법으로 작성합니다.
https://github.com/kosslab-kr/kosshack2016/blob/master/daily/02_Titanium_Boiler_Plate_Template/README.md

*\* Markdown 문법 참고
https://gist.github.com/ihoneymon/652be052a0727ad59601

**Comment by wkddnjset** [comment]
이거 와플에서 in progress로 옮기는 건 드래그로 하면되는건가요? 안되서요 ㅠㅠ

**Comment by gimdongwoo** [comment]
github 리파지터리에 초대메일을 보냈는데, 수락을 안해서 그런겁니다.

**Comment by wkddnjset** [comment]
푸쉬하려는데 이런 오류가 뜹니다! 
git -c diff.mnemonicprefix=false -c core.quotepath=false push -v --tags --set-upstream origin master:master
Fatal: ArgumentException encountered.

Fatal: ArgumentException encountered.

Pushing to https://github.com/kosslab-kr/Titanium-BrandNew
To https://github.com/kosslab-kr/Titanium-BrandNew
 ! [rejected]        master -> master (fetch first)

error: failed to push some refs to 'https://github.com/kosslab-kr/Titanium-BrandNew'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing

hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

오류가 나면서 완료됨.

**Comment by gimdongwoo** [comment]
! [rejected] master -> master (fetch first)
라고 써 있죠~
fetch후에 pull 한다음에 commit하고 push해야 합니다.
원격 리파지터리에 push분량이 있기 때문입니다.

**Comment by wkddnjset** [comment]
오 pull 하는데
git -c diff.mnemonicprefix=false -c core.quotepath=false fetch origin

git -c diff.mnemonicprefix=false -c core.quotepath=false pull origin master
From https://github.com/kosslab-kr/Titanium-BrandNew
- branch            master     -> FETCH_HEAD

fatal: refusing to merge unrelated histories

오류가 나면서 완료됨. 
이러네요 ㅠㅠ

**Comment by gimdongwoo** [comment]
souretree가 어떤 상태인지 캡쳐 좀 올려봐요.
git에서 너무 헤매네요...

**Comment by gimdongwoo** [comment]
로컬의 변경점은 commit을 해서 uncommited change가 없는 상태에서 fetch-pull하면 로컬의 commit과 merge 해서 다시 commit하고 push 하는 것입니다.

**Comment by wkddnjset** [comment]
미션 컴프맀
